# Generated by Django 3.2 on 2021-05-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_subject_choosen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='subject_choosen',
            new_name='category',
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.CharField(max_length=10)),
                ('question_text', models.CharField(max_length=200)),
                ('selected_choice', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
    ]
