# Generated by Django 3.2 on 2013-09-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210530_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answersheet',
            old_name='exam',
            new_name='exam_id',
        ),
        migrations.AddField(
            model_name='answersheet',
            name='choice_1',
            field=models.CharField(default='choice_1', max_length=200),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='choice_2',
            field=models.CharField(default='choice_2', max_length=200),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='choice_3',
            field=models.CharField(default='choice_3', max_length=200),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='choice_4',
            field=models.CharField(default='choice_4', max_length=200),
        ),
    ]
