# Generated by Django 3.2 on 2021-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20130913_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='obtained_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_score',
            field=models.FloatField(default=20),
        ),
    ]
