# Generated by Django 3.2 on 2021-05-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20210530_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='answer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='question_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='question_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='selected_choice',
            field=models.CharField(default='', max_length=200),
        ),
    ]
