# Generated by Django 3.2 on 2021-05-30 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20210530_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answersheet',
            old_name='exam_id',
            new_name='exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
