# Generated by Django 3.2 on 2013-09-12 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0009_auto_20130913_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.FloatField(default=20)),
                ('obtained_score', models.FloatField(default=0)),
                ('category', models.CharField(default='Mixed', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.CharField(default='', max_length=10)),
                ('question_text', models.CharField(default='', max_length=200)),
                ('choice_1', models.CharField(default='choice_1', max_length=200)),
                ('choice_2', models.CharField(default='choice_2', max_length=200)),
                ('choice_3', models.CharField(default='choice_3', max_length=200)),
                ('choice_4', models.CharField(default='choice_4', max_length=200)),
                ('answer', models.CharField(default='', max_length=200)),
                ('selected_choice', models.CharField(default='', max_length=200)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
    ]
