# Generated by Django 3.2 on 2021-05-31 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_answersheet_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
