# Generated by Django 3.2 on 2021-06-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
