# Generated by Django 3.2 on 2021-05-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='general', max_length=200),
        ),
    ]
