# Generated by Django 3.2 on 2021-05-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_master', '0005_auto_20210528_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('History', 'History'), ('General Knowledge', 'General Knowledge'), ('English', 'English')], default='General Knowledge', max_length=200),
        ),
    ]
