# Generated by Django 3.2 on 2021-05-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_master', '0006_auto_20210528_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('History', 'History'), ('General Knowledge', 'General Knowledge'), ('English', 'English')], default='General Knowledge', max_length=200),
        ),
    ]
